//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bi.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SYS_ROLE
    {
        public string ROLE_ID { get; set; }
        public string ROLE_NAME { get; set; }
        public string ROLE_TYPE { get; set; }
        public string DESCR { get; set; }
        public byte IS_ADMIN { get; set; }
        public byte STATUS { get; set; }
    }
}
